#!/bin/bash

echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT."
echo "# This file lists all contributors to the repository."
echo "# See hack/generate-authors.sh to make modifications."

# List all contributors to the repository, sorted by number of commits
git shortlog -sn --all |
awk '{print $2}' |
while read author; do
    # Remove the leading '+' from the email address, if present
    email=$(git log --format="%ae" HEAD | grep -o '[^+]*@.*$' | head -n1 | sed 's/^\+//')
    # Output the author and their email address
    echo "${author} <${email}>"
done
